[build]
  publish = "."  # This is the root directory where your HTML file is located
  command = "npm install && npm run build"  # Adjust the command if you have a different build step

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
